
 select * from customer_behaviour
--Total revenue generated by male & female 

select gender,sum(purchase_amount) as revenue
from customer_behaviour
group by gender;

--which customer used discount but still spent more than the avg spent amount

select customer_id,purchase_amount
from customer_behaviour
where discount_applied = 'yes'  and purchase_amount >= (select avg(purchase_amount) from  customer_behaviour)
 

 --what is the revenue contribution of each age group
select age,sum(purchase_amount) as total_revenue
from customer_behaviour
group by age
order by  total_revenue desc;

--segment customer into new,returning & loyal based on thr total number of previous purchase
-- and show the count of each segment

with customer_type as(
select customer_id,previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	END as customer_segment
	from customer_behaviour)
select  customer_segment,count(*) as "no. of customers"
from customer_type
group by customer_segment

--compare avg shipping amount b/w std & express

select shipping_type,round(avg(purchase_amount),2) as avrage_shipping
from customer_behaviour
where shipping_type in('standard','Express')
group by shipping_type

--subscription status of customers who r repeat buyers(more than 5 previous purchase)

select subscription_status,count(customer_id) as repeat_buyers
from customer_behaviour
where previous_purchases > 5
group by subscription_status